gcc が必要になっていたので base image を変更
```
× Running setup.py install for typed-ast did not run successfully.
│ exit code: 1
╰─> [23 lines of output]
    running install
    /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-311
    creating build/lib.linux-x86_64-cpython-311/typed_ast
    copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
    copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
    copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
    copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
    creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
    copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
    running build_ext
    building '_ast27' extension
    creating build/temp.linux-x86_64-cpython-311
    creating build/temp.linux-x86_64-cpython-311/ast27
    creating build/temp.linux-x86_64-cpython-311/ast27/Custom
    creating build/temp.linux-x86_64-cpython-311/ast27/Parser
    creating build/temp.linux-x86_64-cpython-311/ast27/Python
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iast27/Include -I/usr/local/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
    error: command 'gcc' failed: No such file or directory
    [end of output]
```